### ISSUE TITLE
Shell command "threads" doesn't work in Jython

### ISSUE THREAD

**Issue by tcalmant** [tcalmant/ipopo#27]
``sys._current_frames()`` is not available in Jython, therefore *threads* and *thread* shell commands fail.

```
$ threads
ERROR:pelix.shell.core:Error calling default.threads: '<reflected field public org.python.core.PyObject o' object has no attribute '_current_frames'
Traceback (most recent call last):
  File "C:\jython2.7b3\Lib\site-packages\pelix\shell\core.py", line 703, in execute
    result = method(io_handler, *args, **kwargs)
  File "C:\jython2.7b3\Lib\site-packages\pelix\shell\core.py", line 1152, in threads_list
    frames = sys._current_frames()
AttributeError: '<reflected field public org.python.core.PyObject o' object has no attribute '_current_frames'
```

**Comment by tcalmant** [comment]
The threads command works on Pypy and Pypy3 nearly like in CPython (except Pypy doesn't let access to the value of the frame locals).

It doesn't interesting enough to implement this feature on other interpreters, as they might not give access to the state of threads others than the calling one.

If somebody thinks this feature is important, feel free to reopen the issue.
